# Glibc is required for Factorio Server binaries to run
FROM frolvlad/alpine-glibc

ENV FACTORIO_VERSION=latest \
    MANAGER_VERSION=0.8.2 \
    ADMIN_USER=admin \
    ADMIN_PASS=factorio \
    RCON_PASS="" \
    COOKIE_ENCRYPTION_KEY=""

VOLUME /opt/fsm-data /opt/factorio/saves /opt/factorio/mods /opt/factorio/config

EXPOSE 80/tcp 34197/udp

RUN apk add --no-cache curl tar xz unzip jq

WORKDIR /opt

# Install FSM
COPY factorio-server-manager-linux.zip /factorio-server-manager-linux.zip
RUN unzip /factorio-server-manager-linux.zip \
    && rm /factorio-server-manager-linux.zip \
    && mv factorio-server-manager fsm

COPY entrypoint.sh /opt

ENTRYPOINT ["/opt/entrypoint.sh"]
